version: '2.1'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    environment:
     - POSTGRES_USER=parta
     - POSTGRES_PASSWORD=12345
     - POSTGRES_DB=parta
    ports:
      - "8000:8000"
    volumes:
      - .:/parta
    tty: true
    restart: always
    command: sh -c "./docker/wait-for.sh -c 'nc -z db 5432' -t 30 && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=parta
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=parta
    volumes:
      - ./docker/postgresql:/var/lib/postgresql
    expose:
     - "5432"
  redis:
    image: redis:alpine
  celeryworker:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: sh -c "./docker/celery/worker.sh"
    volumes:
      - .:/parta
    environment:
     - POSTGRES_USER=parta
     - POSTGRES_PASSWORD=12345
     - POSTGRES_DB=parta
    tty: true
    depends_on:
      - db
      - redis
  celerybeat:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: sh -c "./docker/celery/beat.sh"
    volumes:
      - .:/parta
    environment:
     - POSTGRES_USER=parta
     - POSTGRES_PASSWORD=12345
     - POSTGRES_DB=parta
    tty: true
    depends_on:
      - db
      - redis