parameters:
    mailer_user: 'test@example.com'

fos_user:
    db_driver: orm
    firewall_name: api
    user_class: App\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"