# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-15 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def create_social_media(apps, schema_editor):
    SocialMedia = apps.get_model('reports', 'SocialMedia')

    SocialMedia.objects.create(
        name='Facebook',
        service_type='api',
    )

    SocialMedia.objects.create(
        name='Twitter',
        service_type='scrapper',
    )


def delete_social_media(apps, schema_editor):
    SocialMedia = apps.get_model('reports', 'SocialMedia')
    SocialMedia.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('service_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Medias',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='social_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_media_reports', to='reports.SocialMedia'),
        ),
        migrations.RunPython(create_social_media, delete_social_media),
    ]
