FansBundle\Entity\pages:
    type: entity
    table: null
    repositoryClass: FansBundle\Repository\pagesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        page:
            type: string
            length: '100'
            unique: true
    lifecycleCallbacks: {  }
