<?php

namespace FansBundle\Repository;

/**
 * pages_dataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pages_dataRepository extends \Doctrine\ORM\EntityRepository
{
}
